import { useEffect, useState } from 'react'
import QRCode from 'qrcode'
import { emptyPhoneStatus, type PhoneStatus } from '../../shared/phoneMic'

export function PhoneMicrophoneSettings() {
  const [status, setStatus] = useState<PhoneStatus>(emptyPhoneStatus)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [qr, setQr] = useState('')
  const [selected, setSelected] = useState(0)
  const url = status.urls[selected] ?? status.urls[0] ?? ''
  // Setup uses HTTP solely to deliver the public certificate. Once trusted,
  // the secure page link skips setup. Its actual port is supplied by that page;
  // keep the QR aimed at setup so non-default port fallback cannot go stale.
  useEffect(() => {
    let active = true
    const off = window.flow.phone.onStatus(next => { if (active) setStatus(next) })
    void window.flow.phone.get().then(next => { if (active) setStatus(next) }).catch(err => { if (active) setError(err.message) })
    return () => { active = false; off() }
  }, [])
  useEffect(() => {
    let active = true; setQr('')
    if (url) void QRCode.toDataURL(url, { width: 224, margin: 2, errorCorrectionLevel: 'M' }).then(data => { if (active) setQr(data) }).catch(() => {})
    return () => { active = false }
  }, [url])
  const toggle = async () => {
    setBusy(true); setError('')
    try { setStatus(await (status.running ? window.flow.phone.stop() : window.flow.phone.start())) }
    catch (err) { setError((err as Error).message) }
    finally { setBusy(false) }
  }
  return <div style={{ display: 'grid', gap: 10 }}>
    <p style={{ margin: 0, fontSize: 12 }}>Open the phone page in Chrome on the same Wi-Fi. Keep it visible and your phone unlocked.</p>
    <button className="btn" disabled={busy} onClick={() => { void toggle() }}>{busy ? 'Please wait…' : status.running ? 'Stop phone server' : 'Start phone server'}</button>
    {status.running && <>
      <strong role="status">{status.ready ? 'Phone microphone connected' : status.connected ? 'Pairing — waiting for audio…' : 'Waiting for your phone'}</strong>
      <meter aria-label="Phone microphone input level" min={0} max={1} value={status.level} style={{ width: '100%' }} />
      {status.urls.length > 1 && <select className="input" aria-label="Phone network address" value={selected} onChange={e => setSelected(Number(e.target.value))}>{status.urls.map((link, index) => <option key={link} value={index}>{new URL(link).host}</option>)}</select>}
      {qr && <img src={qr} width={180} height={180} alt="Scan to open your private phone microphone setup page" />}
      <code style={{ fontSize: 12, overflowWrap: 'anywhere' }}>{url.split('#')[0]}</code>
      <button className="btn btn-ghost" onClick={() => { void navigator.clipboard.writeText(url).catch(() => setError('Could not copy pairing link. Use the QR code.')) }}>Copy private pairing link</button>
      <p style={{ margin: 0, fontSize: 11 }}>Scan the QR code with Chrome on your iPhone. The page walks through one-time certificate installation and trust, then opens the microphone. If iOS only downloads the certificate in Chrome, open the setup link in Safari to install it, then return to Chrome for the microphone.</p>
      <details><summary>Certificate and connection help</summary><p style={{ fontSize: 11 }}>Only trust the certificate generated by your own Mac. Installing it adds a certificate authority to your phone; remove its profile when you no longer use it. Compare this SHA-256 fingerprint with the certificate:</p><code style={{ fontSize: 10, overflowWrap: 'anywhere' }}>{status.fingerprint}</code><p style={{ fontSize: 11 }}>If the page cannot load or pairing times out, your guest Wi-Fi may isolate devices. Use a private Wi-Fi network with both devices connected. Restart the server after changing networks, then scan the fresh QR code.</p></details>
      <button className="btn" disabled={!status.ready} onClick={() => { setError(''); void window.flow.phone.dictate().catch(err => setError(err.message)) }}>Start / stop dictation</button>
      <small>Keyboard and mouse shortcuts still work. This button also works without a global shortcut.</small>
    </>}
    {(error || status.error) && <span role="alert" style={{ color: 'var(--danger)', fontSize: 12 }}>{error || status.error}</span>}
  </div>
}
